summarizer_config:
  type: M2RAGVLMSummarizer
  params:
    tag: ~

    model_config:
      type: OpenAIVLM
      params:
        model: gpt-4o-2024-08-06
        openai_api_key: ~
        openai_base_url: ~
        use_local_image_file: True
        image_to_base64: True
        resize_image:
          - 512
          - 512

    # model_config:
    #   type: OpenAIVLM
    #   params:
    #     model: step-1o-vision-32k
    #     openai_api_key: ~
    #     openai_base_url: https://api.stepfun.com/v1
    #     use_local_image_file: True
    #     image_to_base64: True
    #     resize_image:
    #       - 512
    #       - 512

    # model_config:
    #   type: DashScopeVLM
    #   params:
    #     model: qwen-vl-max-0809
    #     tokenizer_path: Qwen/Qwen2-VL-72B-Instruct
    #     dashscope_api_key: ~
    #     use_local_image_file: False
    #     image_to_base64: False
    
    # model_config:
    #   type: VLLMVLM
    #   params:
    #     model: llama-3.2-90b-vision-instruct
    #     tokenizer_path: meta-llama/Llama-3.2-90B-Vision-Instruct
    #     vllm_api_key: ~
    #     vllm_service_url: ~
    #     use_local_image_file: True
    #     image_to_base64: True
    #     resize_image:
    #       - 512
    #       - 512

    # model_config:
    #   type: VLLMVLM
    #   params:
    #     model: qwen2-vl-72b-instruct
    #     tokenizer_path: Qwen/Qwen2-VL-72B-Instruct
    #     vllm_api_key: ~
    #     vllm_service_url: ~
    #     use_local_image_file: True
    #     image_to_base64: True
    #     resize_image:
    #       - 512
    #       - 512
    
    # model_config:
    #   type: VLLMVLM
    #   params:
    #     model: llama-3.2-11b-vision-instruct
    #     tokenizer_path: meta-llama/Llama-3.2-11B-Vision-Instruct
    #     vllm_api_key: ~
    #     vllm_service_url: ~
    #     use_local_image_file: True
    #     image_to_base64: True
    #     resize_image:
    #       - 512
    #       - 512

    # model_config:
    #   type: VLLMVLM
    #   params:
    #     model: qwen2-vl-7b-instruct
    #     tokenizer_path: Qwen/Qwen2-VL-7B-Instruct
    #     vllm_api_key: ~
    #     vllm_service_url: ~
    #     use_local_image_file: True
    #     image_to_base64: True
    #     resize_image:
    #       - 512
    #       - 512

    max_samples: ~
    
    max_pieces: ~
    max_pieces_per_sample: 20
    min_piece_score: 3
    max_tokens_per_sample: 8192

    max_images: 10
    max_images_per_sample: 5
    max_aux_images: 5
    max_image_score: 1.0e+10
    min_image_score: 3
    
    output_detailed_caption: False
    multi_stage: False
    use_orig_image: False
dry_run: False
multi_thread_config:
  num_threads: 10
  max_retry_on_failure: 0
  log_warning_on_failure: True
  mark_as_completed_on_failure: False
  timeout: ~
log_dir: ./log
levels: [1]
