### model
model_name_or_path: ./models/Qwen2.5-7B-Instruct/original
adapter_name_or_path: ./models/Qwen2.5-7B-Instruct/LoRA
template: qwen
finetuning_type: lora

### export
export_dir: ./models/Qwen2.5-7B-Instruct/merged
export_size: 2
export_device: cpu
export_legacy_format: false